Allow Custom fields
getconnect/connect-net-sdk pull request #10
Opened 2017-02-16 04:52 UTC by elliott-pd

Add Custom fields implementation.
Will throw ArgumentException if a reserved property is used e.g. Select or Filter.

2017-02-20 02:11 UTC, AdamPD requested changes

2017-02-20 02:11 UTC, AdamPD commented on src/ConnectSdk/Querying/ReservedQueryKeys.cs
> +        public static string Collection = "collection";
I'm not loving this - looks like we're going to have to keep a big list of these at all times.  Is there any other way?

2017-02-20 02:11 UTC, AdamPD commented on src/ConnectSdk/Querying/Query.cs
> +            var tempDictionary = _data.ToDictionary(pair => pair.Key, pair => pair.Value);
I don't really like this - before it was so much cleaner.  How can we keep it the old way?

2017-02-20 02:11 UTC, AdamPD commented on src/ConnectSdk/Querying/Query.cs
> +            if (value == null)
If we did go with this - an extension method would be much better.  I'm still not loving it though.

2017-02-20 02:35 UTC, elliott-pd commented on src/ConnectSdk/Querying/Query.cs
> +            var tempDictionary = _data.ToDictionary(pair => pair.Key, pair => pair.Value);
We can create an ExpandoObject (or a dynamic object) and apply each of the key value pairs to it, then apply our properties over the top and have that converted to a string. This does still have the issue that if we did want to add more properties to the Query class we have to remember to add them to this object in the ToString.

The issue comes down to how the JsonConverter handles our object. If we want each of the key value pairs to be appended to the Query object as properties we cannot do that dynamically as it's a typed class. 

If we can merge two JSON objects taking the properties from a second one we could convert the dictionary to a JSON object, then the apply the Query object over the top and return the result. That way we wouldn't have to keep track of individual properties, and we could drop the ReservedQueryKeys class, I do like that class though as we can then throw exceptions based on reserved key words. Preventing the user from trying to go `.Custom("select", {})` etc

2017-02-22 02:03 UTC, AdamPD approved these changes
Much nicer.

2017-02-22 04:01 UTC, merged